/*
 * Copyright (c) 2024 ASMlover. All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 *  * Redistributions of source code must retain the above copyright
 *    notice, this list ofconditions and the following disclaimer.
 *
 *  * Redistributions in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in
 *    the documentation and/or other materialsprovided with the
 *    distribution.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
 * BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
 * ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 */
#if !defined(WREN_OPCODE)
#	define WREN_OPCODE(name, effect)
#endif

WREN_OPCODE(CONSTANT, 1)
WREN_OPCODE(NULL, 1)
WREN_OPCODE(FALSE, 1)
WREN_OPCODE(TRUE, 1)

WREN_OPCODE(LOAD_LOCAL_0, 1)
WREN_OPCODE(LOAD_LOCAL_1, 1)
WREN_OPCODE(LOAD_LOCAL_2, 1)
WREN_OPCODE(LOAD_LOCAL_3, 1)
WREN_OPCODE(LOAD_LOCAL_4, 1)
WREN_OPCODE(LOAD_LOCAL_5, 1)
WREN_OPCODE(LOAD_LOCAL_6, 1)
WREN_OPCODE(LOAD_LOCAL_7, 1)
WREN_OPCODE(LOAD_LOCAL_8, 1)

WREN_OPCODE(LOAD_LOCAL, 1)
WREN_OPCODE(STORE_LOCAL, 0)
WREN_OPCODE(LOAD_UPVALUE, 1)
WREN_OPCODE(STORE_UPVALUE, 0)
WREN_OPCODE(LOAD_MODULE_VAR, 1)
WREN_OPCODE(STORE_MODULE_VAR, 0)
WREN_OPCODE(LOAD_FIELD_THIS, 1)
WREN_OPCODE(STORE_FIELD_THIS, 0)
WREN_OPCODE(LOAD_FIELD, 0)
WREN_OPCODE(STORE_FIELD, -1)

WREN_OPCODE(POP, -1)

WREN_OPCODE(CALL_0, 0)
WREN_OPCODE(CALL_1, -1)
WREN_OPCODE(CALL_2, -2)
WREN_OPCODE(CALL_3, -3)
WREN_OPCODE(CALL_4, -4)
WREN_OPCODE(CALL_5, -5)
WREN_OPCODE(CALL_6, -6)
WREN_OPCODE(CALL_7, -7)
WREN_OPCODE(CALL_8, -8)
WREN_OPCODE(CALL_9, -9)
WREN_OPCODE(CALL_10, -10)
WREN_OPCODE(CALL_11, -11)
WREN_OPCODE(CALL_12, -12)
WREN_OPCODE(CALL_13, -13)
WREN_OPCODE(CALL_14, -14)
WREN_OPCODE(CALL_15, -15)
WREN_OPCODE(CALL_16, -16)

WREN_OPCODE(SUPER_0, 0)
WREN_OPCODE(SUPER_1, -1)
WREN_OPCODE(SUPER_2, -2)
WREN_OPCODE(SUPER_3, -3)
WREN_OPCODE(SUPER_4, -4)
WREN_OPCODE(SUPER_5, -5)
WREN_OPCODE(SUPER_6, -6)
WREN_OPCODE(SUPER_7, -7)
WREN_OPCODE(SUPER_8, -8)
WREN_OPCODE(SUPER_9, -9)
WREN_OPCODE(SUPER_10, -10)
WREN_OPCODE(SUPER_11, -11)
WREN_OPCODE(SUPER_12, -12)
WREN_OPCODE(SUPER_13, -13)
WREN_OPCODE(SUPER_14, -14)
WREN_OPCODE(SUPER_15, -15)
WREN_OPCODE(SUPER_16, -16)

WREN_OPCODE(JUMP, 0)
WREN_OPCODE(LOOP, 0)
WREN_OPCODE(JUMP_IF, -1)
WREN_OPCODE(AND, -1)
WREN_OPCODE(OR, -1)
WREN_OPCODE(CLOSE_UPVALUE, -1)
WREN_OPCODE(RETURN, 0)

WREN_OPCODE(CLOSURE, 1)
WREN_OPCODE(CONSTRUCT, 0)
WREN_OPCODE(FOREIGN_CONSTRUCT, 0)
WREN_OPCODE(CLASS, -1)
WREN_OPCODE(FOREIGN_CLASS, -1)
WREN_OPCODE(METHOD_INSTANCE, -2)
WREN_OPCODE(METHOD_STATIC, -2)

WREN_OPCODE(END_MODULE, 1)
WREN_OPCODE(IMPORT_MODULE, 1)
WREN_OPCODE(IMPORT_VARIABLE, 1)

WREN_OPCODE(END, 0)

#undef WREN_OPCODE
