#ifndef MS_TOKEN_H_
#define MS_TOKEN_H_

#include <stddef.h>

typedef enum MsTokenKind {
  MS_TOKEN_LEFT_PAREN,
  MS_TOKEN_RIGHT_PAREN,
  MS_TOKEN_LEFT_BRACE,
  MS_TOKEN_RIGHT_BRACE,
  MS_TOKEN_LEFT_BRACKET,
  MS_TOKEN_RIGHT_BRACKET,
  MS_TOKEN_COMMA,
  MS_TOKEN_DOT,
  MS_TOKEN_MINUS,
  MS_TOKEN_PLUS,
  MS_TOKEN_SEMICOLON,
  MS_TOKEN_SLASH,
  MS_TOKEN_STAR,
  MS_TOKEN_COLON,
  MS_TOKEN_BANG,
  MS_TOKEN_BANG_EQUAL,
  MS_TOKEN_EQUAL,
  MS_TOKEN_EQUAL_EQUAL,
  MS_TOKEN_GREATER,
  MS_TOKEN_GREATER_EQUAL,
  MS_TOKEN_LESS,
  MS_TOKEN_LESS_EQUAL,
  MS_TOKEN_IDENTIFIER,
  MS_TOKEN_STRING,
  MS_TOKEN_NUMBER,
  MS_TOKEN_VAR,
  MS_TOKEN_FN,
  MS_TOKEN_RETURN,
  MS_TOKEN_CLASS,
  MS_TOKEN_SELF,
  MS_TOKEN_SUPER,
  MS_TOKEN_PRINT,
  MS_TOKEN_IMPORT,
  MS_TOKEN_FROM,
  MS_TOKEN_AS,
  MS_TOKEN_IF,
  MS_TOKEN_ELSE,
  MS_TOKEN_WHILE,
  MS_TOKEN_FOR,
  MS_TOKEN_BREAK,
  MS_TOKEN_CONTINUE,
  MS_TOKEN_AND,
  MS_TOKEN_OR,
  MS_TOKEN_TRUE,
  MS_TOKEN_FALSE,
  MS_TOKEN_NIL,
  MS_TOKEN_NEWLINE,
  MS_TOKEN_EOF
} MsTokenKind;

typedef struct MsToken {
  MsTokenKind kind;
  const char *start;
  size_t length;
  int line;
  int column;
  int end_column;
} MsToken;

const char *ms_token_kind_name(MsTokenKind kind);

#endif