#ifndef TOKDEF
# define TOKDEF(K, S)
#endif

#ifndef TOKEN
# define TOKEN(K, S) TOKDEF(TK_##K, S)
#endif

#ifndef PUNCTUATOR
# define PUNCTUATOR(K, S) TOKEN(K, S)
#endif

#ifndef KEYWORD
# define KEYWORD(K, S) TOKDEF(KW_##K, S)
#endif

PUNCTUATOR(LPAREN, "(")
PUNCTUATOR(RPAREN, ")")
PUNCTUATOR(LBRACE, "{")
PUNCTUATOR(RBRACE, "}")
PUNCTUATOR(COMMA, ",")
PUNCTUATOR(MINUS, "-")
PUNCTUATOR(PLUS, "+")
PUNCTUATOR(SEMI, ";")
PUNCTUATOR(SLASH, "/")
PUNCTUATOR(STAR, "*")
PUNCTUATOR(EQ, "=")

TOKEN(IDENTIFIER, "IDENTIFIER")
TOKEN(NUMERIC, "NUMERIC")
TOKEN(STRING, "STRING")

KEYWORD(FALSE, "false")
KEYWORD(FN, "fn")
KEYWORD(NIL, "nil")
KEYWORD(TRUE, "true")
KEYWORD(VAR, "var")

TOKEN(EOF, "EOF")
TOKEN(ERR, "ERR")

#undef KEYWORD
#undef PUNCTUATOR
#undef TOKEN
#undef TOKDEF