# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ClientGate.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import service as _service
from google.protobuf import service_reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import Common_pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='ClientGate.proto',
  package='Mars.Server',
  serialized_pb=_b('\n\x10\x43lientGate.proto\x12\x0bMars.Server\x1a\x0c\x43ommon.proto\"\"\n\x0b\x45ncryptText\x12\x13\n\x0b\x65ncryptText\x18\x01 \x02(\x0c\"\x1b\n\x0bSessionSeed\x12\x0c\n\x04seed\x18\x01 \x02(\x03\"X\n\nSessionKey\x12\x13\n\x0bpaddingHead\x18\x01 \x02(\x0c\x12\x12\n\nsessionKey\x18\x02 \x02(\x0c\x12\x0c\n\x04seed\x18\x03 \x02(\x03\x12\x13\n\x0bpaddingTail\x18\x04 \x02(\x0c\x32\xb1\x02\n\x0cSClient2Gate\x12\x33\n\x0bseedRequest\x12\x11.Mars.Server.Null\x1a\x11.Mars.Server.Null\x12\x39\n\nsessionKey\x12\x18.Mars.Server.EncryptText\x1a\x11.Mars.Server.Null\x12@\n\x0e\x63onnectRequest\x12\x1b.Mars.Server.ConnectRequest\x1a\x11.Mars.Server.Null\x12\x36\n\tentityRpc\x12\x16.Mars.Server.EntityRpc\x1a\x11.Mars.Server.Null\x12\x37\n\x0bregMd5Index\x12\x15.Mars.Server.Md5Index\x1a\x11.Mars.Server.Null2\xf3\x03\n\x0cSGate2Client\x12<\n\ronSeedRequest\x12\x18.Mars.Server.SessionSeed\x1a\x11.Mars.Server.Null\x12\x34\n\x0conSessionKey\x12\x11.Mars.Server.Null\x1a\x11.Mars.Server.Null\x12@\n\x10onConnectRequest\x12\x19.Mars.Server.ConnectReply\x1a\x11.Mars.Server.Null\x12<\n\x0eonCreateEntity\x12\x17.Mars.Server.EntityData\x1a\x11.Mars.Server.Null\x12=\n\x0fonDestroyEntity\x12\x17.Mars.Server.EntityData\x1a\x11.Mars.Server.Null\x12\x38\n\x0bonEntityRpc\x12\x16.Mars.Server.EntityRpc\x1a\x11.Mars.Server.Null\x12=\n\x0e\x63hatWithClient\x12\x18.Mars.Server.OutBandData\x1a\x11.Mars.Server.Null\x12\x37\n\x0bregMd5Index\x12\x15.Mars.Server.Md5Index\x1a\x11.Mars.Server.NullB\x03\x90\x01\x01')
  ,
  dependencies=[Common_pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_ENCRYPTTEXT = _descriptor.Descriptor(
  name='EncryptText',
  full_name='Mars.Server.EncryptText',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='encryptText', full_name='Mars.Server.EncryptText.encryptText', index=0,
      number=1, type=12, cpp_type=9, label=2,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=47,
  serialized_end=81,
)


_SESSIONSEED = _descriptor.Descriptor(
  name='SessionSeed',
  full_name='Mars.Server.SessionSeed',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='seed', full_name='Mars.Server.SessionSeed.seed', index=0,
      number=1, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=83,
  serialized_end=110,
)


_SESSIONKEY = _descriptor.Descriptor(
  name='SessionKey',
  full_name='Mars.Server.SessionKey',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='paddingHead', full_name='Mars.Server.SessionKey.paddingHead', index=0,
      number=1, type=12, cpp_type=9, label=2,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='sessionKey', full_name='Mars.Server.SessionKey.sessionKey', index=1,
      number=2, type=12, cpp_type=9, label=2,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='seed', full_name='Mars.Server.SessionKey.seed', index=2,
      number=3, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='paddingTail', full_name='Mars.Server.SessionKey.paddingTail', index=3,
      number=4, type=12, cpp_type=9, label=2,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=112,
  serialized_end=200,
)

DESCRIPTOR.message_types_by_name['EncryptText'] = _ENCRYPTTEXT
DESCRIPTOR.message_types_by_name['SessionSeed'] = _SESSIONSEED
DESCRIPTOR.message_types_by_name['SessionKey'] = _SESSIONKEY

EncryptText = _reflection.GeneratedProtocolMessageType('EncryptText', (_message.Message,), dict(
  DESCRIPTOR = _ENCRYPTTEXT,
  __module__ = 'ClientGate_pb2'
  # @@protoc_insertion_point(class_scope:Mars.Server.EncryptText)
  ))
_sym_db.RegisterMessage(EncryptText)

SessionSeed = _reflection.GeneratedProtocolMessageType('SessionSeed', (_message.Message,), dict(
  DESCRIPTOR = _SESSIONSEED,
  __module__ = 'ClientGate_pb2'
  # @@protoc_insertion_point(class_scope:Mars.Server.SessionSeed)
  ))
_sym_db.RegisterMessage(SessionSeed)

SessionKey = _reflection.GeneratedProtocolMessageType('SessionKey', (_message.Message,), dict(
  DESCRIPTOR = _SESSIONKEY,
  __module__ = 'ClientGate_pb2'
  # @@protoc_insertion_point(class_scope:Mars.Server.SessionKey)
  ))
_sym_db.RegisterMessage(SessionKey)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\220\001\001'))

_SCLIENT2GATE = _descriptor.ServiceDescriptor(
  name='SClient2Gate',
  full_name='Mars.Server.SClient2Gate',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=203,
  serialized_end=508,
  methods=[
  _descriptor.MethodDescriptor(
    name='seedRequest',
    full_name='Mars.Server.SClient2Gate.seedRequest',
    index=0,
    containing_service=None,
    input_type=Common_pb2._NULL,
    output_type=Common_pb2._NULL,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='sessionKey',
    full_name='Mars.Server.SClient2Gate.sessionKey',
    index=1,
    containing_service=None,
    input_type=_ENCRYPTTEXT,
    output_type=Common_pb2._NULL,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='connectRequest',
    full_name='Mars.Server.SClient2Gate.connectRequest',
    index=2,
    containing_service=None,
    input_type=Common_pb2._CONNECTREQUEST,
    output_type=Common_pb2._NULL,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='entityRpc',
    full_name='Mars.Server.SClient2Gate.entityRpc',
    index=3,
    containing_service=None,
    input_type=Common_pb2._ENTITYRPC,
    output_type=Common_pb2._NULL,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='regMd5Index',
    full_name='Mars.Server.SClient2Gate.regMd5Index',
    index=4,
    containing_service=None,
    input_type=Common_pb2._MD5INDEX,
    output_type=Common_pb2._NULL,
    options=None,
  ),
])

SClient2Gate = service_reflection.GeneratedServiceType('SClient2Gate', (_service.Service,), dict(
  DESCRIPTOR = _SCLIENT2GATE,
  __module__ = 'ClientGate_pb2'
  ))

SClient2Gate_Stub = service_reflection.GeneratedServiceStubType('SClient2Gate_Stub', (SClient2Gate,), dict(
  DESCRIPTOR = _SCLIENT2GATE,
  __module__ = 'ClientGate_pb2'
  ))



_SGATE2CLIENT = _descriptor.ServiceDescriptor(
  name='SGate2Client',
  full_name='Mars.Server.SGate2Client',
  file=DESCRIPTOR,
  index=1,
  options=None,
  serialized_start=511,
  serialized_end=1010,
  methods=[
  _descriptor.MethodDescriptor(
    name='onSeedRequest',
    full_name='Mars.Server.SGate2Client.onSeedRequest',
    index=0,
    containing_service=None,
    input_type=_SESSIONSEED,
    output_type=Common_pb2._NULL,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='onSessionKey',
    full_name='Mars.Server.SGate2Client.onSessionKey',
    index=1,
    containing_service=None,
    input_type=Common_pb2._NULL,
    output_type=Common_pb2._NULL,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='onConnectRequest',
    full_name='Mars.Server.SGate2Client.onConnectRequest',
    index=2,
    containing_service=None,
    input_type=Common_pb2._CONNECTREPLY,
    output_type=Common_pb2._NULL,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='onCreateEntity',
    full_name='Mars.Server.SGate2Client.onCreateEntity',
    index=3,
    containing_service=None,
    input_type=Common_pb2._ENTITYDATA,
    output_type=Common_pb2._NULL,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='onDestroyEntity',
    full_name='Mars.Server.SGate2Client.onDestroyEntity',
    index=4,
    containing_service=None,
    input_type=Common_pb2._ENTITYDATA,
    output_type=Common_pb2._NULL,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='onEntityRpc',
    full_name='Mars.Server.SGate2Client.onEntityRpc',
    index=5,
    containing_service=None,
    input_type=Common_pb2._ENTITYRPC,
    output_type=Common_pb2._NULL,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='chatWithClient',
    full_name='Mars.Server.SGate2Client.chatWithClient',
    index=6,
    containing_service=None,
    input_type=Common_pb2._OUTBANDDATA,
    output_type=Common_pb2._NULL,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='regMd5Index',
    full_name='Mars.Server.SGate2Client.regMd5Index',
    index=7,
    containing_service=None,
    input_type=Common_pb2._MD5INDEX,
    output_type=Common_pb2._NULL,
    options=None,
  ),
])

SGate2Client = service_reflection.GeneratedServiceType('SGate2Client', (_service.Service,), dict(
  DESCRIPTOR = _SGATE2CLIENT,
  __module__ = 'ClientGate_pb2'
  ))

SGate2Client_Stub = service_reflection.GeneratedServiceStubType('SGate2Client_Stub', (SGate2Client,), dict(
  DESCRIPTOR = _SGATE2CLIENT,
  __module__ = 'ClientGate_pb2'
  ))


# @@protoc_insertion_point(module_scope)
