
//******************************************************************************
// RCF - Remote Call Framework
//
// Copyright (c) 2005 - 2013, Delta V Software. All rights reserved.
// http://www.deltavsoft.com
//
// RCF is distributed under dual licenses - closed source or GPL.
// Consult your particular license for conditions of use.
//
// If you have not purchased a commercial license, you are using RCF 
// under GPL terms.
//
// Version: 2.0
// Contact: support <at> deltavsoft.com 
//
//******************************************************************************

#undef RCF_BEGIN
#undef RCF_BEGIN_I0
#undef RCF_BEGIN_I1
#undef RCF_BEGIN_I2
#undef RCF_END

#define RCF_BEGIN RCF_BEGIN_INLINE
#define RCF_BEGIN_I0 RCF_BEGIN_I0_INLINE
#define RCF_BEGIN_I1 RCF_BEGIN_I1_INLINE
#define RCF_BEGIN_I2 RCF_BEGIN_I2_INLINE
#define RCF_END RCF_END_INLINE

#undef RCF_METHOD_R0
#undef RCF_METHOD_R1
#undef RCF_METHOD_R2
#undef RCF_METHOD_R3
#undef RCF_METHOD_R4
#undef RCF_METHOD_R5
#undef RCF_METHOD_R6
#undef RCF_METHOD_R7
#undef RCF_METHOD_R8
#undef RCF_METHOD_R9
#undef RCF_METHOD_R10
#undef RCF_METHOD_R11
#undef RCF_METHOD_R12
#undef RCF_METHOD_R13
#undef RCF_METHOD_R14
#undef RCF_METHOD_R15

#undef RCF_METHOD_V0
#undef RCF_METHOD_V1
#undef RCF_METHOD_V2
#undef RCF_METHOD_V3
#undef RCF_METHOD_V4
#undef RCF_METHOD_V5
#undef RCF_METHOD_V6
#undef RCF_METHOD_V7
#undef RCF_METHOD_V8
#undef RCF_METHOD_V9
#undef RCF_METHOD_V10
#undef RCF_METHOD_V11
#undef RCF_METHOD_V12
#undef RCF_METHOD_V13
#undef RCF_METHOD_V14
#undef RCF_METHOD_V15

#define RCF_METHOD_R0 RCF_METHOD_R0_INLINE
#define RCF_METHOD_R1 RCF_METHOD_R1_INLINE
#define RCF_METHOD_R2 RCF_METHOD_R2_INLINE
#define RCF_METHOD_R3 RCF_METHOD_R3_INLINE
#define RCF_METHOD_R4 RCF_METHOD_R4_INLINE
#define RCF_METHOD_R5 RCF_METHOD_R5_INLINE
#define RCF_METHOD_R6 RCF_METHOD_R6_INLINE
#define RCF_METHOD_R7 RCF_METHOD_R7_INLINE
#define RCF_METHOD_R8 RCF_METHOD_R8_INLINE
#define RCF_METHOD_R9 RCF_METHOD_R9_INLINE
#define RCF_METHOD_R10 RCF_METHOD_R10_INLINE
#define RCF_METHOD_R11 RCF_METHOD_R11_INLINE
#define RCF_METHOD_R12 RCF_METHOD_R12_INLINE
#define RCF_METHOD_R13 RCF_METHOD_R13_INLINE
#define RCF_METHOD_R14 RCF_METHOD_R14_INLINE
#define RCF_METHOD_R15 RCF_METHOD_R15_INLINE

#define RCF_METHOD_V0 RCF_METHOD_V0_INLINE
#define RCF_METHOD_V1 RCF_METHOD_V1_INLINE
#define RCF_METHOD_V2 RCF_METHOD_V2_INLINE
#define RCF_METHOD_V3 RCF_METHOD_V3_INLINE
#define RCF_METHOD_V4 RCF_METHOD_V4_INLINE
#define RCF_METHOD_V5 RCF_METHOD_V5_INLINE
#define RCF_METHOD_V6 RCF_METHOD_V6_INLINE
#define RCF_METHOD_V7 RCF_METHOD_V7_INLINE
#define RCF_METHOD_V8 RCF_METHOD_V8_INLINE
#define RCF_METHOD_V9 RCF_METHOD_V9_INLINE
#define RCF_METHOD_V10 RCF_METHOD_V10_INLINE
#define RCF_METHOD_V11 RCF_METHOD_V11_INLINE
#define RCF_METHOD_V12 RCF_METHOD_V12_INLINE
#define RCF_METHOD_V13 RCF_METHOD_V13_INLINE
#define RCF_METHOD_V14 RCF_METHOD_V14_INLINE
#define RCF_METHOD_V15 RCF_METHOD_V15_INLINE
