// generated automatically from auxiliary\meta.wren, do not edit

static const str_t kLibSource =
"\n"
"class Meta {\n"
"  static getModuleVariables(module) {\n"
"    if (!(module is String)) Fiber.abort(\"module name must be a string\")\n"
"    var result = getModuleVars(module)\n"
"    if (result != nil) return result\n"
"\n"
"    Fiber.abort(\"could not find the module named `\" + module + \"`\")\n"
"  }\n"
"\n"
"  static eval(source_bytes) {\n"
"    if (!source_bytes is String) Fiber.abort(\"source code must be a string\")\n"
"\n"
"    var fiber = compile_(source_bytes, false, false)\n"
"    if (fiber == nil) Fiber.abort(\"could not compile source code\")\n"
"\n"
"    fiber.call()\n"
"  }\n"
"\n"
"  static compileExpression(source_bytes) {\n"
"    if (!(source_bytes is String)) Fiber.abort(\"source code must be a string\")\n"
"    return compile_(source_bytes, true, true)\n"
"  }\n"
"\n"
"  static compile(source_bytes) {\n"
"    if (!(source_bytes is String)) Fiber.abort(\"source code must be a string\")\n"
"    return compile_(source_bytes, false, true)\n"
"  }\n"
"\n"
"  foreign static compile_(source, is_expression, print_errors)\n"
"  foreign static getModuleVars(module)\n"
"}\n";
