# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: BasicProtocol.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import service as _service
from google.protobuf import service_reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import Common_pb2 as Common__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='BasicProtocol.proto',
  package='Nyx.Core',
  syntax='proto3',
  serialized_pb=_b('\n\x13\x42\x61sicProtocol.proto\x12\x08Nyx.Core\x1a\x0c\x43ommon.proto\"$\n\rEncryptString\x12\x13\n\x0b\x65ncrypt_str\x18\x01 \x01(\x0c\"\x1b\n\x0bSessionSeed\x12\x0c\n\x04seed\x18\x01 \x01(\x03\"i\n\nSessionKey\x12\x1b\n\x13random_padding_head\x18\x01 \x01(\x0c\x12\x13\n\x0bsession_key\x18\x02 \x01(\x0c\x12\x0c\n\x04seed\x18\x03 \x01(\x03\x12\x1b\n\x13random_padding_tail\x18\x04 \x01(\x0c\x32\xa0\x02\n\rSClientToGate\x12.\n\x0crequest_seed\x12\x0e.Nyx.Core.Void\x1a\x0e.Nyx.Core.Void\x12\x36\n\x0bsession_key\x12\x17.Nyx.Core.EncryptString\x1a\x0e.Nyx.Core.Void\x12\x38\n\x0c\x63onnect_gate\x12\x18.Nyx.Core.ConnectRequest\x1a\x0e.Nyx.Core.Void\x12\x39\n\x0e\x65ntity_message\x12\x17.Nyx.Core.EntityMessage\x1a\x0e.Nyx.Core.Void\x12\x32\n\x0creg_md5index\x12\x12.Nyx.Core.Md5Index\x1a\x0e.Nyx.Core.Void2\xd0\x03\n\rSGateToClient\x12\x38\n\x0fon_request_seed\x12\x15.Nyx.Core.SessionSeed\x1a\x0e.Nyx.Core.Void\x12\x30\n\x0eon_session_key\x12\x0e.Nyx.Core.Void\x1a\x0e.Nyx.Core.Void\x12<\n\x0fon_connect_gate\x12\x19.Nyx.Core.ConnectResponse\x1a\x0e.Nyx.Core.Void\x12\x35\n\rcreate_entity\x12\x14.Nyx.Core.EntityInfo\x1a\x0e.Nyx.Core.Void\x12\x36\n\x0e\x64\x65stroy_entity\x12\x14.Nyx.Core.EntityInfo\x1a\x0e.Nyx.Core.Void\x12\x39\n\x0e\x65ntity_message\x12\x17.Nyx.Core.EntityMessage\x1a\x0e.Nyx.Core.Void\x12\x37\n\x0e\x63hat_to_client\x12\x15.Nyx.Core.OutbandInfo\x1a\x0e.Nyx.Core.Void\x12\x32\n\x0creg_md5index\x12\x12.Nyx.Core.Md5Index\x1a\x0e.Nyx.Core.VoidB\x06\x80\x01\x01\x90\x01\x01\x62\x06proto3')
  ,
  dependencies=[Common__pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_ENCRYPTSTRING = _descriptor.Descriptor(
  name='EncryptString',
  full_name='Nyx.Core.EncryptString',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='encrypt_str', full_name='Nyx.Core.EncryptString.encrypt_str', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=47,
  serialized_end=83,
)


_SESSIONSEED = _descriptor.Descriptor(
  name='SessionSeed',
  full_name='Nyx.Core.SessionSeed',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='seed', full_name='Nyx.Core.SessionSeed.seed', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=85,
  serialized_end=112,
)


_SESSIONKEY = _descriptor.Descriptor(
  name='SessionKey',
  full_name='Nyx.Core.SessionKey',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='random_padding_head', full_name='Nyx.Core.SessionKey.random_padding_head', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='session_key', full_name='Nyx.Core.SessionKey.session_key', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='seed', full_name='Nyx.Core.SessionKey.seed', index=2,
      number=3, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='random_padding_tail', full_name='Nyx.Core.SessionKey.random_padding_tail', index=3,
      number=4, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=114,
  serialized_end=219,
)

DESCRIPTOR.message_types_by_name['EncryptString'] = _ENCRYPTSTRING
DESCRIPTOR.message_types_by_name['SessionSeed'] = _SESSIONSEED
DESCRIPTOR.message_types_by_name['SessionKey'] = _SESSIONKEY

EncryptString = _reflection.GeneratedProtocolMessageType('EncryptString', (_message.Message,), dict(
  DESCRIPTOR = _ENCRYPTSTRING,
  __module__ = 'BasicProtocol_pb2'
  # @@protoc_insertion_point(class_scope:Nyx.Core.EncryptString)
  ))
_sym_db.RegisterMessage(EncryptString)

SessionSeed = _reflection.GeneratedProtocolMessageType('SessionSeed', (_message.Message,), dict(
  DESCRIPTOR = _SESSIONSEED,
  __module__ = 'BasicProtocol_pb2'
  # @@protoc_insertion_point(class_scope:Nyx.Core.SessionSeed)
  ))
_sym_db.RegisterMessage(SessionSeed)

SessionKey = _reflection.GeneratedProtocolMessageType('SessionKey', (_message.Message,), dict(
  DESCRIPTOR = _SESSIONKEY,
  __module__ = 'BasicProtocol_pb2'
  # @@protoc_insertion_point(class_scope:Nyx.Core.SessionKey)
  ))
_sym_db.RegisterMessage(SessionKey)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\200\001\001\220\001\001'))

_SCLIENTTOGATE = _descriptor.ServiceDescriptor(
  name='SClientToGate',
  full_name='Nyx.Core.SClientToGate',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=222,
  serialized_end=510,
  methods=[
  _descriptor.MethodDescriptor(
    name='request_seed',
    full_name='Nyx.Core.SClientToGate.request_seed',
    index=0,
    containing_service=None,
    input_type=Common__pb2._VOID,
    output_type=Common__pb2._VOID,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='session_key',
    full_name='Nyx.Core.SClientToGate.session_key',
    index=1,
    containing_service=None,
    input_type=_ENCRYPTSTRING,
    output_type=Common__pb2._VOID,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='connect_gate',
    full_name='Nyx.Core.SClientToGate.connect_gate',
    index=2,
    containing_service=None,
    input_type=Common__pb2._CONNECTREQUEST,
    output_type=Common__pb2._VOID,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='entity_message',
    full_name='Nyx.Core.SClientToGate.entity_message',
    index=3,
    containing_service=None,
    input_type=Common__pb2._ENTITYMESSAGE,
    output_type=Common__pb2._VOID,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='reg_md5index',
    full_name='Nyx.Core.SClientToGate.reg_md5index',
    index=4,
    containing_service=None,
    input_type=Common__pb2._MD5INDEX,
    output_type=Common__pb2._VOID,
    options=None,
  ),
])

SClientToGate = service_reflection.GeneratedServiceType('SClientToGate', (_service.Service,), dict(
  DESCRIPTOR = _SCLIENTTOGATE,
  __module__ = 'BasicProtocol_pb2'
  ))

SClientToGate_Stub = service_reflection.GeneratedServiceStubType('SClientToGate_Stub', (SClientToGate,), dict(
  DESCRIPTOR = _SCLIENTTOGATE,
  __module__ = 'BasicProtocol_pb2'
  ))



_SGATETOCLIENT = _descriptor.ServiceDescriptor(
  name='SGateToClient',
  full_name='Nyx.Core.SGateToClient',
  file=DESCRIPTOR,
  index=1,
  options=None,
  serialized_start=513,
  serialized_end=977,
  methods=[
  _descriptor.MethodDescriptor(
    name='on_request_seed',
    full_name='Nyx.Core.SGateToClient.on_request_seed',
    index=0,
    containing_service=None,
    input_type=_SESSIONSEED,
    output_type=Common__pb2._VOID,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='on_session_key',
    full_name='Nyx.Core.SGateToClient.on_session_key',
    index=1,
    containing_service=None,
    input_type=Common__pb2._VOID,
    output_type=Common__pb2._VOID,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='on_connect_gate',
    full_name='Nyx.Core.SGateToClient.on_connect_gate',
    index=2,
    containing_service=None,
    input_type=Common__pb2._CONNECTRESPONSE,
    output_type=Common__pb2._VOID,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='create_entity',
    full_name='Nyx.Core.SGateToClient.create_entity',
    index=3,
    containing_service=None,
    input_type=Common__pb2._ENTITYINFO,
    output_type=Common__pb2._VOID,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='destroy_entity',
    full_name='Nyx.Core.SGateToClient.destroy_entity',
    index=4,
    containing_service=None,
    input_type=Common__pb2._ENTITYINFO,
    output_type=Common__pb2._VOID,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='entity_message',
    full_name='Nyx.Core.SGateToClient.entity_message',
    index=5,
    containing_service=None,
    input_type=Common__pb2._ENTITYMESSAGE,
    output_type=Common__pb2._VOID,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='chat_to_client',
    full_name='Nyx.Core.SGateToClient.chat_to_client',
    index=6,
    containing_service=None,
    input_type=Common__pb2._OUTBANDINFO,
    output_type=Common__pb2._VOID,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='reg_md5index',
    full_name='Nyx.Core.SGateToClient.reg_md5index',
    index=7,
    containing_service=None,
    input_type=Common__pb2._MD5INDEX,
    output_type=Common__pb2._VOID,
    options=None,
  ),
])

SGateToClient = service_reflection.GeneratedServiceType('SGateToClient', (_service.Service,), dict(
  DESCRIPTOR = _SGATETOCLIENT,
  __module__ = 'BasicProtocol_pb2'
  ))

SGateToClient_Stub = service_reflection.GeneratedServiceStubType('SGateToClient_Stub', (SGateToClient,), dict(
  DESCRIPTOR = _SGATETOCLIENT,
  __module__ = 'BasicProtocol_pb2'
  ))


# @@protoc_insertion_point(module_scope)
